version: "3.8"

services:
  broker-1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kraft-broker-1
    hostname: broker-1
    restart: unless-stopped
    ports:
      - "19092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:9093,EXTERNAL://${HOST_IP:?Set HOST_IP to the machine IP}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-1:9094,2@broker-2:9094,3@broker-3:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # CLUSTER_ID must be a base64-encoded UUID (22 chars, no padding).
      CLUSTER_ID: ${CLUSTER_ID:-kp7Rzc7oT4GtsqDuqo21Wg}

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_SUPER_USERS: User:${KAFKA_ADMIN_USER:-admin}
    volumes:
      - ./data/broker-1:/var/lib/kafka/data

  broker-2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kraft-broker-2
    hostname: broker-2
    restart: unless-stopped
    ports:
      - "29092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:9093,EXTERNAL://${HOST_IP:?Set HOST_IP to the machine IP}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-1:9094,2@broker-2:9094,3@broker-3:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: ${CLUSTER_ID:-kp7Rzc7oT4GtsqDuqo21Wg}

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_SUPER_USERS: User:${KAFKA_ADMIN_USER:-admin}
    volumes:
      - ./data/broker-2:/var/lib/kafka/data

  broker-3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kraft-broker-3
    hostname: broker-3
    restart: unless-stopped
    ports:
      - "39092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:9093,EXTERNAL://${HOST_IP:?Set HOST_IP to the machine IP}:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-1:9094,2@broker-2:9094,3@broker-3:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: ${CLUSTER_ID:-kp7Rzc7oT4GtsqDuqo21Wg}

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_ADMIN_USER:-admin}="${KAFKA_ADMIN_PASSWORD:-admin-secret}"
        user_${KAFKA_CLIENT_USER:-client}="${KAFKA_CLIENT_PASSWORD:-client-secret}";
      KAFKA_SUPER_USERS: User:${KAFKA_ADMIN_USER:-admin}
    volumes:
      - ./data/broker-3:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui-multi
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-multi
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:9093,broker-2:9093,broker-3:9093
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USER:-admin}" password="${KAFKA_ADMIN_PASSWORD:-admin-secret}";
    depends_on:
      broker-1:
        condition: service_started
      broker-2:
        condition: service_started
      broker-3:
        condition: service_started
